name: microbiome_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - openpyxl
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-bio
  - snakemake=7.32.4
  - jupyter
  - biopython
  - pip
  - yaml
  - sklearn
