# These are read by both R (beta_diversity.R) and Python
group:
  Fecal_Crohn:   "#AA31B3"
  Oral_Crohn:    "#D192D8"
  Fecal_Healthy: "#547DD3"
  Oral_Healthy:  "#A7BDE7"
  HMP:           "#624097"

synonyms:
  Fecal_Crohn:   ["Crohn-Fecal", "Fecal_Crohn"]
  Oral_Crohn:    ["Crohn-Oral",  "Oral_Crohn"]
  Fecal_Healthy: ["Healthy-Fecal", "Fecal_Healthy"]
  Oral_Healthy:  ["Healthy-Oral",  "Oral_Healthy"]
