name: microbiome_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - openpyxl
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-bio
  - snakemake=7.32.4
  - jupyter
  - biopython
  - pip
  - yaml
  - sklearn
  - r-base=4.3.*
  - r-tidyverse=2.*        # readr, dplyr, tidyr, stringr, purrr, ggplot2
  - r-broom=1.*
  - r-sandwich=3.*
  - r-lmtest=0.*
  - r-effsize=0.*
  - codacore
  - coda4microbiome